In [1]:
import numpy as np

In [9]:
def myHouseholder1(a):
    alpha = np.linalg.norm(a)
    
    if a[0] < 0:
        alpha = -alpha
        
    w = np.zeros_like(a)
    w[0] = a[0] + alpha
    w[1:] = a[1:]
        
    w = w/np.linalg.norm(w)
    return w

In [10]:
def myHouseholder2(A,w):
    
    B = np.dot((np.eye(len(w)) - 2*np.outer(w,w)),A)
    
    return B

In [11]:
# Example 1:

A = np.array([[12, 10, 4],
             [10, 8, -5],
             [4, -5, 3]])

a = A[:,0]
w = myHouseholder1(a)
B = myHouseholder2(A, w)

print("Example 1:")
print("Original Matrix, A: \n", A)
print("Householder vector, w: \n", w)
print("Modified matrix, B: \n", B)

Example 1:
Original Matrix, A: 
 [[12 10  4]
 [10  8 -5]
 [ 4 -5  3]]
Householder vector, w: 
 [0.93333333 0.33333333 0.13333333]
Modified matrix, B: 
 [[-16.12444444 -11.15555556  -0.60444444]
 [ -0.04444444   0.44444444  -6.64444444]
 [ -0.01777778  -8.02222222   2.34222222]]


In [12]:
# Example 2:

A = np.array([[4.75, 2.25, -0.25],
             [2.25, 4.75, 1.25],
             [-0.25, 1.25, 4.75]])

a = A[:,0]
w = myHouseholder1(a)
B = myHouseholder2(A, w)

print("Example 1:")
print("Original Matrix, A: \n", A)
print("Householder vector, w: \n", w)
print("Modified matrix, B: \n", B)

Example 1:
Original Matrix, A: 
 [[ 4.75  2.25 -0.25]
 [ 2.25  4.75  1.25]
 [-0.25  1.25  4.75]]
Householder vector, w: 
 [ 0.97537614  0.21919898 -0.02435544]
Modified matrix, B: 
 [[-5.26189129e+00 -4.00283830e+00 -8.31450092e-02]
 [ 2.14238349e-16  3.34478237e+00  1.28749778e+00]
 [ 2.77555756e-17  1.40613529e+00  4.74583358e+00]]
